package gophernews

// Item cannot be autogenerated as a struct, as it should not be represented as a struct
// Item has varying fields, and not all fields will be returned for any single call
type Item map[string]interface{}

func (i Item) By() string {
	s, _ := i["by"].(string)
	return s
}

func (i Item) ID() int {
	s, _ := i["id"].(float64)
	return int(s)
}

func (i Item) Kids() []int {
	kids, _ := i["kids"]
	fsi, _ := kids.([]interface{})
	is := make([]int, len(fsi))
	for i, f := range fsi {
		is[i] = int(f.(float64))
	}
	return is
}

func (i Item) Parent() int {
	s, _ := i["parent"].(float64)
	return int(s)
}

func (i Item) Parts() []int {
	parts, _ := i["parts"]
	fsi, _ := parts.([]interface{})
	is := make([]int, len(fsi))
	for i, f := range fsi {
		is[i] = int(f.(float64))
	}
	return is
}

func (i Item) Score() int {
	s, _ := i["score"].(float64)
	return int(s)
}

func (i Item) Text() string {
	s, _ := i["text"].(string)
	return s
}

func (i Item) Time() int {
	s, _ := i["time"].(float64)
	return int(s)
}

func (i Item) Title() string {
	s, _ := i["title"].(string)
	return s
}

func (i Item) Type() string {
	s, _ := i["type"].(string)
	return s
}

func (i Item) URL() string {
	s, _ := i["url"].(string)
	return s
}
